### ISSUE TITLE
EU version

### ISSUE THREAD

**Issue by cickma** [giordanidev/aion-classic-mods#1]
Hello,

Thank you for the mods.
Is there a way to make it work for the European version?.
I have done all the steps but I cannot make it work and I think is because I use the European version of Aion classics.

Thank you

**Comment by giordanidev** [comment]
Hello there! What exactly is not working?

The only thing that should not be working os the chat filter unfortunately. But that is a issue with the GF client not loading the filter file.

**Comment by cickma** [comment]
> Hello there! What exactly is not working?
> The Jap font
> The only thing that should not be working is the chat filter unfortunately. But that is a issue with the GF client not loading the filter file.
> Also, for the EU version you should copy and paste the files into your game directory manually. Those scripts only work for NA.
> I did but still didn't work
> I do have a newer version that works for EU here: https://github.com/giordanidev/aion-classic-mods-py/releases/tag/v1.0.0
I installed this version and now it is working!! thank you!!

**Comment by giordanidev** [comment]
I'm glad it worked. Have fun!!!
